# Site settings
title: BIOS Engineer Stuff
footertitle: x86 BIOS Developer
email: kurtqiao@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  kurtqiao©2015-Powered by Jekyll
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://kurtqiao.github.io" # the base hostname & protocol for your site
twitter_username: kurtqiao
github_username:  kurtqiao

# Build settings
markdown: kramdown
